### ISSUE TITLE
Typo Found in word Artifact

### ISSUE THREAD

**Issue by amykmeyers** [nikantonelli/Planning-Poker#3]
Hi Nik,
Great app, but I think there is a typo in the error message that appears when there is no description.  
![image](https://user-images.githubusercontent.com/17934558/80986162-09395180-8de5-11ea-9c80-4012ff86e58a.png)
![2020-05-04_08-55-16](https://user-images.githubusercontent.com/17934558/80986175-0dfe0580-8de5-11ea-9cde-3962d5f11d2c.png)

**Comment by nikantonelli** [comment]
I think it may be because I am British...😉

https://www.merriam-webster.com/dictionary/artefact

**Comment by amykmeyers** [comment]
Haha sorry!
