### ISSUE TITLE
Easier Visualization that I voted

### ISSUE THREAD

**Issue by amykmeyers** [nikantonelli/Planning-Poker#4]
Hi Nik,
We are reviewing this app as a team and really receiving positive feedback.  One issue is that many folks on the team weren't sure they voted.  It is pretty subtle that the white dotted box goes away.  Is there a way to add an indicator to let someone know they already voted?  Additionally, there was a question as to whether it would be possible to show the timer on the voters page?

**Comment by nikantonelli** [comment]
New code uploaded. It puts more info into the size line now and turns the underline 'red' is there is something to do.

The timer is running in the context of the moderator and there is no synchronous way to signal its state to the users. The best solution would be for the moderator to share their screen via hangout, webex, zoom, etc. Or just say: "Starting 10 second timer..... 5 seconds left....

**Comment by amykmeyers** [comment]
Wow!  Thanks @nikantonelli for the quick response.  We will load and test.  We expected the timer was just a moderator action, but never hurts to ask the question :-)
